[workspace]
channels = ["conda-forge"]
name = "ECE484-assignment1"
platforms = ["linux-64"]
version = "1.0.0"

[tasks]
# Run public tests only (for students during development)
tests = "pytest -v -s tests"
# Run tests for Q4_frameworks
tests_q4 = "pytest -v -s tests/test_Q4.py"
# Run tests for Q5_synthesis
tests_q5 = "pytest -v -s tests/test_Q5.py"
# Run tests for Q6a_SwapTest
tests_q6a = "pytest -v -s tests/test_Q6a.py"
# Run tests for Q6b_BernsteinVazirani
tests_q6b = "pytest -v tests/test_Q6b.py"
# Format code using black (auto-format Python files)
format = "black src tests || true"
# Lint code using ruff (check for code style issues)
lint = "ruff check src tests || true"
# Run Python interpreter in the pixi environment
python = "python"

[dependencies]
python = ">=3.11,<3.12"

[pypi-dependencies]
pennylane = ">=0.43.2, <0.44"
qiskit-aer = ">=0.17.2, <0.18"
qiskit = ">=2.3.0, <3"
qiskit-ibm-runtime = ">=0.45.0, <0.46"
numpy = ">=2.4.1, <3"
pytest = ">=9.0.2, <10"
black = ">=25.12.0, <26"
ruff = ">=0.14.11, <0.15"
pyyaml = ">=6.0.3, <7"
pytest-xdist = ">=3.8.0, <4"
qutip = ">=5.2.2, <6"
qpic = ">=1.1.0, <2"
